agent.sources = kafka-source
agent.channels = memory-channel
agent.sinks = files
# agent.sinks = log
agent.sources.kafka-source.interceptors = i1
agent.sources.kafka-source.interceptors.i1.type = timestamp
# source
agent.sources.kafka-source.type = org.apache.flume.source.kafka.KafkaSource
agent.sources.kafka-source.kafka.bootstrap.servers = localhost:9092
agent.sources.kafka-source.kafka.topics = tg-msg, tg-msg-react
agent.sources.kafka-source.consumer.group.id = tg-msg-group
agent.sources.kafka-source.channels = memory-channel
# sinks
agent.sinks.files.channel = memory-channel
agent.sinks.files.type = hdfs
agent.sinks.files.hdfs.path = #LINK TO YOUR S3
agent.sinks.files.hdfs.fileType = DataStream
agent.sinks.files.hdfs.filePrefix = log
agent.sinks.files.hdfs.rollInterval = 1800
agent.sinks.s3-sink.hdfs.rollCount = 20
agent.sinks.s3-sink.hdfs.batchSize = 20
agent.sinks.s3-sink.hdfs.compress = true
# agent.sinks.log.channel = memory-channel
# agent.sinks.log.type = logger
# channels
agent.channels.memory-channel.type = memory
agent.channels.memory-channel.capacity = 10000
agent.channels.memory-channel.transactionCapacity = 1000